name: Deploy to GitHub Pages

on:

  workflow_dispatch:

  push:
    branches:
      - main
  schedule:
    - cron: '15 00 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:

      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Eleventy and Dependencies
        run: |
          npm init -y
          npm install @11ty/eleventy --save-dev
          npm install @11ty/eleventy-fetch --save-dev

      - name: Create Eleventy Configuration File
        run: |

          echo "module.exports = function(eleventyConfig) { eleventyConfig.addGlobalData(\"permalink\", \"{{ page.fileSlug }}.html\"); return { dir: { input: 'src', output: '_site' } };" > .eleventy.js

      - name: Copy existing files to Eleventy source folder
        run: |

          rsync -av --exclude 'node_modules/' --exclude '.git/' --exclude '.github/' --exclude 'src/' . src

      - name: Build site with Eleventy
        run: npm run start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
          cname: chrishoch.co.uk
