name: Simple GitHub Workflow

on:
  # This trigger allows you to manually run the workflow from the GitHub Actions UI.
  workflow_dispatch:

  #  existing triggers for automated deployments.
  push:
    branches:
      - main
  schedule:
    - cron: '15 00 * * *'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Project list with their repository and file paths
      PROJECTS: '[{"id": "plex-webhooks", "repo": "home_assistant", "path": "blueprints/plex_webhook_handler/plex_webhook_release.yaml"}, {"id": "jellyfin_status", "repo": "jellyfin_status"}, {"id": "PiCOW-Garage", "repo": "PiCOW-Garage"}, {"id": "powershell", "repo": "powershell"}]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and format last commit dates
        id: get_dates
        run: |
          # Create the destination directory
          mkdir -p ./assets/github/commit_times

          # Use jq to parse the JSON array and loop through it
          jq -c '.[]' <<< "$PROJECTS" | while read -r project; do
            id=$(echo "$project" | jq -r '.id')
            repo=$(echo "$project" | jq -r '.repo')
            path=$(echo "$project" | jq -r '.path')

            # Build the correct API URL based on if a path is provided
            if [ -n "$path" ]; then
              api_url="https://api.github.com/repos/thenextbutton/$repo/commits?per_page=1&path=$(echo "$path" | jq -sRr @uri)"
            else
              api_url="https://api.github.com/repos/thenextbutton/$repo/commits?per_page=1"
            fi

            # Fetch the commit date from the API
            commit_date=$(curl -s -H "Authorization: token $GH_TOKEN" "$api_url" | jq -r '.[0].commit.committer.date')
            
            # Format the date to ISO 8601
            formatted_date=$(date -Iseconds -d "$commit_date")
            
            # Create a file for each project in the specified directory
            echo "$formatted_date" > "./assets/github/commit_times/$id.txt"
          done

      - name: Deploy last updated files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./assets/github/commit_times/
          keep_files: true
          publish_branch: main
